#!/bin/sh
#
# comment out a section to turn that check off
# commit without checks by adding --no-verify to your commit command

# run Black on all .py files
printf "\n\e[1mRunning Black Python code formatter\e[0m\n"
hash black 2>/dev/null || { echo >&2 "Black not installed in this environment. Halting commit."; exit 1; }
black .

# run flake8 on all .py files
printf "\n\e[1mRunning flake8 Python linter\e[0m\n"
hash flake8 2>/dev/null || { echo >&2 "flake8 not installed in this environment. Halting commit."; exit 1; }
flake8 .



exec < /dev/tty
while read -p "Continue with commit? (Y/n) " yn; do
    case $yn in
        [Yy] ) printf "Continuing with commit\n"; break;;
        [Nn] ) printf "Cancelling commit\n"; exit 1;;
        * ) echo "Please answer y (yes) or n (no):" && continue;
    esac
done
